site_name: Cable-Tester Docs


plugins:
  - search      # Плагін пошуку по сторінкам сайту
  - awesome-pages
  - table-reader:   # Плагін дає можливість рендирити markdown таблиці, посилаючись на їх файл (наприклад .csv)
        allow_missing_files: True
  - drawio:
        toolbar: false  # control if hovering on a diagram shows a toolbar for zooming or not (default: true)
        tooltips: true # control if tooltips will be shown (default: true)
        edit: true     # control if edit button will be shown in the lightbox view (default: true)
        border: 0     # increase or decrease the border / margin around your diagrams (default: 5)
        darkmode: false # support darkmode. allows for automatic switching between dark and lightmode based on the theme toggle. (default: false)
  - glightbox:
        background: none
        auto_caption: true
        skip_classes:
            - no-zoom
  - git-revision-date-localized:        # Плагін, для відображення дати і часу створення md сторінок (дані бере з локального репозиторія, папка .git). Для роботи потрібно мати доступ до термінального git
        locale: uk
        timezone: Europe/Kyiv           # Часовий пояс
        enable_creation_date: false     # Чи відображати дату створення сторінки
        type: custom                    # Формат дати/часу (можливі значення: date, datetime, iso_date, iso_datetime, timeago, custom)
        custom_format: "%d.%m.%Y (%H:%M)"  # Кастомний формат виводу


markdown_extensions:
  - toc:
        permalink: true
        permalink_title: Якірне посилання на цей розділ для довідки
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
        alternate_style: true
  - md_in_html
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme: 
    name: material
    language: uk
    logo: assets/images/logo.png
    favicon: assets/images/favicon.ico
    palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Вибрати сторону зла

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Вибрати сторону добра
    features:
      - content.tooltips
      #- navigation.tabs
      - navigation.sections
      - navigation.top
      - toc.follow
      - content.code.copy
      - navigation.indexes
      
extra:
  generator: false

extra_css: # Кастомні стилі CSS
  - assets/stylesheets/git-revision-date-localized-plugin.css # Дата останнього редагування
  - assets/stylesheets/tables-custom.css # Кастомні стилі MarkDown таблиць

extra_javascript:
  - assets/javascripts/tables-selector.js # Скрипт для можливості виділення рядків таблиці
  - assets/javascripts/tables-sort.js # Скрипт для можливості сортування вмісту таблиць 

validation:
  absolute_links: ignore